Include optional Ipni-Cid-Schema-Type HTTP header
ipni/go-libipni pull request #221
Opened 2024-08-30 19:05 UTC by gammazero

This optional header, when present, serves as an indication to advertisement publishers what type of data is being requested and is identified by the CID. This may help some publishers more quickly lookup the data.

Implements fix for https://github.com/ipni/storetheindex/issues/2662

2024-08-30 23:13 UTC, willscott commented
github actions seems to be pretty unhappy about the references here - are you missing a file / definition?

2024-09-03 04:48 UTC, willscott approved these changes

2024-09-03 08:24 UTC, masih requested changes
Blockers: 
* exposed context key for schema type
* check that returned node matches the expected type from link system.
* match IPLD schema types exactly for header values.

Otherwise, LGTM. Left some suggestions.
Thank you for getting this done @gammazero 🍻

2024-09-03 08:24 UTC, masih commented on dagsync/ipnisync/cid_schema_hint.go
> +	CidSchemaEntries = "entries"
Use type name [consistent with schema](https://github.com/ipni/go-libipni/blob/main/ingest/schema/schema.ipldsch#L3)?

2024-09-03 08:24 UTC, masih commented on dagsync/ipnisync/cid_schema_hint.go
> +	CidSchemaAd = "advertisement"
Match the [casing of schema](https://github.com/ipni/go-libipni/blob/main/ingest/schema/schema.ipldsch#L40)?

I would also add a link to the schema in godoc while at it.

2024-09-03 08:24 UTC, masih commented on dagsync/ipnisync/cid_schema_hint.go
> +const CidSchemaCtxKey cidSchemaTypeCtxKey = CidSchemaHeader
If exported any user of this package can get/set this. Instead, offer exported getter function for it and keep the setting of the value unexported, exclusive to the package that sets it.

2024-09-03 08:24 UTC, masih commented on dagsync/ipnisync/publisher.go
> +	if reqType != "" {
Validate and fail early if type is unknown?

2024-09-03 08:24 UTC, masih commented on dagsync/ipnisync/sync.go
> +	cidSchemaType, ok := ctx.Value(CidSchemaCtxKey).(string)
Ditto re wrapping this logic in a package level function, which would also capture the if statement below and return error if type is unknown.

2024-09-03 08:24 UTC, masih commented on dagsync/ipnisync/sync.go
> +		req.Header.Set(CidSchemaHeader, reqType)
OK to set this for both request and response. We just want to make sure this is documented in the specs somewhere.

2024-09-03 08:24 UTC, masih commented on dagsync/ipnisync/publisher.go
> +	item, err := p.lsys.Load(ipldCtx, cidlink.Link{Cid: c}, basicnode.Prototype.Any)
Why `basicnode.Prototype.Any` if type is set? We probably should return an error if type is set in request and it doesn't match the type we read from link system.

2024-09-03 21:12 UTC, gammazero commented on dagsync/ipnisync/cid_schema_hint.go
> +const CidSchemaCtxKey cidSchemaTypeCtxKey = CidSchemaHeader
It is a `const` so it cannot be set. Also, the type is not exported so a different value of that type cannot be used by an external package.

2024-09-03 21:13 UTC, gammazero commented on dagsync/ipnisync/publisher.go
> +	if reqType != "" {
The reasoning not to:
> The publisher, who receives the Ipni-Cid-Schema-Type HTTP header, does not validate the value, because newer values may need to be received by consumer that is using an older version of library.

2024-09-03 21:23 UTC, masih commented on dagsync/ipnisync/publisher.go
> +	if reqType != "" {
> Consider Boost wanting to use an older version of go-libipni, 

But older versions would not set the header, right? If the header is present then we would validate. otherwise fall back on the old behaviour. 

No?

2024-09-04 01:08 UTC, gammazero commented on dagsync/ipnisync/publisher.go
> +	if reqType != "" {
I mean if boost wants to use this version of go-libipni (this one being older), but both boost and indexer understand some newer hint. This way boost's older version of go-libipni can get the hint from the HTTP header, put then hint into a context and let boost extract extract that hint in its linksystem -- even though boost's go-libipni does not recognize the value of the hint.

2024-09-04 07:46 UTC, masih commented on dagsync/ipnisync/publisher.go
> +	if reqType != "" {
OK

2024-09-04 07:55 UTC, masih approved these changes
There is a minor lint issue that's failing CI, otherwise no blockers. Thanks @gammazero 🚀

2024-09-04 07:55 UTC, masih commented on dagsync/ipnisync/cid_schema_hint.go
> +func CtxWithCidSchema(ctx context.Context, cidSchemaType string) (context.Context, error) {
Going back to previous comments I would make the setter unexported such that the context value can only ever be set by `ipnisync` package. This is a common practice to avoid scope creep. 

I understand that this function is used by `dagsync`; this may be a sign for the need to flatten those packages.

2024-09-05 17:36 UTC, gammazero commented on dagsync/ipnisync/cid_schema_hint.go
> +func CtxWithCidSchema(ctx context.Context, cidSchemaType string) (context.Context, error) {
Flattening those packages is probably the thing to do. Until then, it is necessary to call this from dagsync since it is only there that it is known what the CID refers to. The ipnisync package only tries to fetch according to CID and selector.

2024-09-05 18:05 UTC, merged