Make provider cache threadsafe
ipni/go-libipni pull request #26
Opened 2023-04-28 16:45 UTC by ischasny

* Move provider cache to a separate file
* Make provider cache thread safe so that the double hashed client can be used concurrently
* This optimisation will reduce dhfind latency significantly (at least by a third) as well as will allow to save up on memory

2023-04-28 18:59 UTC, gammazero requested changes
Looks like there is one problem with the response channel that needs to be fixed.

2023-04-28 18:59 UTC, gammazero commented on find/client/http/dhash_client.go
> +				}, nil
How do you know that the channel did not close because of an error?

It looks like the previous logic was actually correct. It would keep reading results from `resChan` until `resChan` closed (finished or error), and then return an error if there was an error, and responses if there was no error.

With the new logic if there is an error there is no guarantee whether it detects the `errChan` returning an error first or `resChan` closing first and it could return a response even if there was only an error.  I think this need to be fixed.

2023-04-28 18:59 UTC, gammazero commented on find/client/http/provider_cache.go
> +		if xmd == nil {
Would it be safer to say
```suggestion
		if len(xmd) == 0 {
```
In case there is an empty byte slice?

2023-04-29 09:07 UTC, ischasny commented on find/client/http/dhash_client.go
> +				}, nil
Good point. Previous logic didn't work because iterating res Cham would hang indefinitely when a error is sent to err chan. Like a deadlock - one goroutine is waiting for res chan to close and the other for a meesage to be taken off the err chan.

2023-04-29 09:17 UTC, ischasny commented on find/client/http/dhash_client.go
> +				}, nil
How would res channel get closed before error is read from err channel? In order for res channel to be closed, something needs to read from err channel first or otherwise the defer clause, where channels get closed, will never be executed. So there is a guarantee that if there was an error it would be received from the error channel first. What am I missing?

2023-04-29 09:47 UTC, ischasny commented on find/client/http/dhash_client.go
> +				}, nil
Just pushed in the change, let me know if that looks better now :) I've set the errChan size to [two](https://github.com/ipni/go-libipni/pull/26/files#diff-380ceda9df4e22cbe4d968ca5cb709f4b8fd8d2c2e13e56f20b5073ac15c566eR74), so it doesn't block.

2023-05-01 09:11 UTC, willscott approved these changes

2023-05-01 16:02 UTC, gammazero approved these changes

2023-05-02 09:02 UTC, merged